#开发环境 生产环境

spring:
  profiles:
    active: dev

mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  #配置SQL日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


#调整界面编码格式
server.tomcat.uri-encoding: UTF-8
server:
  servlet:
    encoding:
      force: true
      enabled: true
      charset: UTF-8